[package]
name = "rdownloader-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] } # 新增 serde 依赖
